package main

import (
	"flag"
	"fmt"
	"io/ioutil"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/prometheus/common/log"

	zkLog "log"
)

const (
	metricsRoute = "/metrics"
)

var (
	version = "unknown"

	listenAddress = flag.String("web.listen-address", ":9381", "Address to listen on for web interface and telemetry.")
	zookeeper = flag.String("zk.addr", "zookeeper:2181", "Zookeeper Address.")
	zkChroot = flag.String("zk.chroot", "/kafka/cluster", "Zookeeper path for kafka cluster.")
	serverTimeout = flag.Duration("web.timeout", 60*time.Second, "Timeout for responding to HTTP requests.")
	zkTimeout     = flag.Duration("zk.timeout", 5*time.Second, "Timeout for ZooKeeper requests")
	showVersion   = flag.Bool("version", false, "Show version and exit")
)

func handler(w http.ResponseWriter, r *http.Request) {
	registry := prometheus.NewRegistry()
	registry.MustRegister(newCollector(*zookeeper, *zkChroot, []string{}))

	h := promhttp.HandlerFor(registry, promhttp.HandlerOpts{})
	h.ServeHTTP(w, r)
}

func main() {
	flag.Parse()

	if *showVersion {
		fmt.Println(version)
		os.Exit(0)
	}

	// kazoo uses ZooKeeper client that logs everything by default, so we end up
	// with duplicated logs we don't control, disable vanilla logger messages
	// and rely on logs generated by our code
	zkLog.SetOutput(ioutil.Discard)

	http.HandleFunc(metricsRoute, handler)
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(`
		<html>
		<head><title>Kafka ZooKeeper Exporter</title></head>
		<body>
		<p><a href='` + metricsRoute + `'>Metrics</a></p></body>
		</html>
		`))
	})

	log.Infoln("Listening on", *listenAddress)

	s := &http.Server{
		Addr:         *listenAddress,
		ReadTimeout:  *serverTimeout,
		WriteTimeout: *serverTimeout,
	}
	log.Fatal(s.ListenAndServe())
}
